server:
  port: 8070

spring:
  datasource:
    platform: mysql
  application:
    name: aks-micservice-gateway
  cloud:
    sentinel:
      transport:
        dashboard: 8088
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
# 配置输出日志
logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.http.server.reactive: DEBUG
    org.springframework.web.reactive: DEBUG
    reactor.ipc.netty: info

#开启端点
management:
  endpoints:
    web:
      exposure:
        include: '*'
#trace: true
